# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
jobs:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx
    osx_image: xcode11.3
cache: packages

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:cran/imagemagick-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
