#' Default parameter documentation
#'
#' This function does not do anything. It is meant to hold argument
#' documentation, which is then inherited in all other functions.
#'
#' @param totaltime Positive numeric. Specifies how the age of the island to be
#'   simulated by [DAISIE::DAISIE_sim_constant_rate()].
#' @param sim_pars Numeric vector with DAISIE simulation parameters, as used by
#'   [DAISIE::DAISIE_sim_constant_rate()]:
#'   1. simID, an integer with the ID of the parameters. Not used in the
#'      simulation.
#'   2. Cladogenesis rate (\eqn{\lambda^c}).
#'   3. Extinction rate \eqn{\mu}.
#'   4. Island-wide carrying capacity (K').
#'   5. Immigration rate \eqn{\gamma}.
#'   6. Anagenesis rate \eqn{\lambda^a}.
#'   7. Totaltime: the island age.
#' @param n_mainland_spec Positive integer with total number of species in the
#'   mainland pool, which can colonize the island.
#' @param iw_sims DAISIE object (list) as generated by [run_iw_sims()].
#' @param param_set Positive integer. Corresponds to one line of the param_space
#'   data frame.
#' @param brts List with vector of branching times as returned by
#' @param n_param_sets_to_run Integer with number of parameter sets (i.e.,
#'   columns in the parameter space file) should be simulated.
#' @param save_to_file Boolean stating if output of pipeline should be saved
#'  as an `.rds` file in `./output/`
#' @param test_seed A boolean, which sets the seed to 1. Defaults to `FALSE`,
#'  should only be set to `TRUE` for testing.
#'
#' @return Nothing
#'
#' @author Pedro Neves
#' @note Should be marked as `@noRd`, but this can't be done or inheriting
#' parameters would not be possible.
default_params_doc <- function(totaltime,
                               sim_pars,
                               n_mainland_spec,
                               iw_sims,
                               param_set,
                               brts,
                               n_param_sets_to_run,
                               save_to_file,
                               test_seed) {
  # Nothing
}
