#' Default parameter documentation
#'
#' This function does not do anything. It is meant to hold argument
#' documentation, which is then inherited in all other functions.
#'
#' @param totaltime Positive numeric. Specifies how the age of the island to be
#'   simulated by [DAISIE::DAISIE_sim_constant_rate()].
#' @param sim_pars Numeric vector with DAISIE simulation parameters, as used by
#'   [DAISIE::DAISIE_sim_constant_rate()]:
#'   1. simID, an integer with the ID of the parameters. Not used in the
#'      simulation.
#'   2. Cladogenesis rate (\eqn{\lambda^c}).
#'   3. Extinction rate \eqn{\mu}.
#'   4. Island-wide carrying capacity (K').
#'   5. Immigration rate \eqn{\gamma}.
#'   6. Anagenesis rate \eqn{\lambda^a}.
#'   7. Totaltime: the island age.
#' @param n_mainland_spec Positive integer with total number of species in the
#'   mainland pool, which can colonize the island.
#' @param n_replicates Positive integer with the total number of replicates of
#'   the same island that should be simulated.
#' @param seed_start Integer specifying the seed of replicate 1. Each replicate
#'   a given param set will be simulated using seed 1:n_replicates.
#' @param iw_sims DAISIE object (list) as generated by [run_iw_sims()].
#' @param param_set Positive integer. Corresponds to one line of the param_space
#'   data frame.
#' @param brts List with vector of branching times as returned by
#'   [DAISIE::DAISIE_sim_constant_rate()].
#'
#' @return Nothing
#'
#' @author Pedro Neves
#' @note Should be marked as `@noRd`, but this can't be done or inheriting
#' parameters would not be possible.
default_params_doc <- function(totaltime,
                               sim_pars,
                               n_mainland_spec,
                               n_replicates,
                               seed_start,
                               iw_sims,
                               param_set,
                               brts) {
  # Nothing
}
